@baseUrl = http://localhost:5000
@apiUrl = api/v1

###
POST {{baseUrl}}/{{apiUrl}}/auth/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "name": "Jane Doe",
  "username": "janedoe",
  "email": "jane@gmail.com",
  "password": "12345678"
}

###
POST {{baseUrl}}/{{apiUrl}}/auth/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "jane@gmail.com",
  "password": "12345678"
}

###
GET {{baseUrl}}/{{apiUrl}}/auth/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{apiUrl}}/auth/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{apiUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "jane@gmail.com"
}

###
POST {{baseUrl}}/{{apiUrl}}/auth/reset-password/d2a3eb957da4616df07a68910dadfb9346cbb28c
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "12345678",
  "confirmPassword": "12345678"
}
